name: Apply
on:
  push:
    branches:
      - main
jobs:
  infra:
    name: Terraform
    environment: production
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: kvrhdn/tfe-run@v1
        with:
          token: ${{ secrets.TFE_TOKEN }}
          organization: tecnoly
          workspace: infrastructure
          message: |
            Run triggered using tfe-run (commit: ${{ github.SHA }})

          directory: ./
          type: apply
          wait-for-completion: true
          tf-vars: |
            credentials_file = "${{ secrets.GCP_CREDENTIALS }}"
            project_id       = "${{ secrets.GCP_PROJECT_ID }}"
            tfe_token        = "${{ secrets.TFE_TOKEN }}"